"""Criando tabela livros

Revision ID: 5cdfd535e492
Revises: 
Create Date: 2026-07-26 11:29:54.611994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cdfd535e492'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('autor', sa.String(length=255), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livros')
    # ### end Alembic commands ###
