"""Criando tabela usuarios

Revision ID: 82581524b31e
Revises: 5cdfd535e492
Create Date: 2026-07-26 12:01:55.130600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82581524b31e'
down_revision = '5cdfd535e492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
