"""criando tabela emprestimos

Revision ID: fdec46fa7f7a
Revises: 82581524b31e
Create Date: 2026-07-26 13:59:54.366433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdec46fa7f7a'
down_revision = '82581524b31e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emprestimos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['livro_id'], ['livros.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emprestimos')
    # ### end Alembic commands ###
